### ISSUE TITLE
Radium.StyleRoot error

### ISSUE THREAD

**Issue by prateekbhatt** [djorg83/react-bootstrap-sweetalert#1]
Throws an error now, with radium v0.17 . Need to update the top-level component according to this:

https://github.com/FormidableLabs/radium/blob/master/docs/guides/upgrade-v0.16.x.md#how-to-make-the-change

**Comment by djorg83** [comment]
Will fix.

**Comment by djorg83** [comment]
Radium removed completely in v2.0
