### ISSUE TITLE
Is it possible to close the pop up by clicking outside

### ISSUE THREAD

**Issue by fabioespinosa** [djorg83/react-bootstrap-sweetalert#15]
Great work in this package 👍 

I was wondering if it was possible to make possible to set the "allowOutsideClick" referenced here to true:

https://github.com/t4t5/sweetalert/issues/81

Thanks a lot!

**Comment by djorg83** [comment]
sure, that is possible

**Comment by fabioespinosa** [comment]
Awesome! 💯

**Comment by tquiroga** [comment]
Indeed, a needed one!

**Comment by tquiroga** [comment]
#20

**Comment by fabioespinosa** [comment]
💯 thanks @tquiroga !

**Comment by djorg83** [comment]
Added to 4.1.0. Enjoy!
