### ISSUE TITLE
do i really need bootstrap for this?

### ISSUE THREAD

**Issue by pantchox** [djorg83/react-bootstrap-sweetalert#17]
Hi,

Looks great implementation! 
there are other implementations  but outdated and not so configurable like this one.
In my project i have my own CSS framework and not interested in using bootstrap (or adding just for this package).
I looked at the package and i saw it uses bootstrap (hence the title of the repo :)

How do i make it use only the needed CSS for sweetalert and no bootstrap.

Thanks!

**Comment by djorg83** [comment]
It really just uses bootstrap for a few things like btn style classes. You
could technically right your own css rules to implement those few styles.

**Comment by pantchox** [comment]
great, so then i can remove any dependencies of the react-bootstrap in the package.json right? since it only uses CSS classes and no other react components - i imply that from what you are saying.
