### ISSUE TITLE
Support close animation (feature request)

### ISSUE THREAD

**Issue by guillaume86** [djorg83/react-bootstrap-sweetalert#18]
Nice job on this component, it would be cool to have support for the close animation too.
The API would need a `show` prop as an alternative to component mounting/unmounting to support animated hide like react-bootstrap does for modals. It's nothing high priority for me but a nice thing to have if possible.

Thanks for your work, have a nice day.

Edit: I just seen the show prop already exists, only the animation is missing then.

**Comment by djorg83** [comment]
This didnt make it for 4.1.0, but it could be in 5.0.

**Comment by wouter140** [comment]
I added support for (custom) show and hide animations in PR #52. 
This can be implemented using the `openAnim` and `closeAnim` properties.
