### ISSUE TITLE
Ignoring inputType='password'

### ISSUE THREAD

**Issue by jfeldstein** [djorg83/react-bootstrap-sweetalert#2]
You can see from the inspector that I'm passing `inputType="password"` to `<SweetAlert .../>` but it is rendering as a plain text:

![screen shot 2016-07-08 at 2 22 24 pm](https://cloud.githubusercontent.com/assets/172683/16701863/8091d88a-4517-11e6-9239-41bfd0df783b.png)

![screen shot 2016-07-08 at 2 23 30 pm](https://cloud.githubusercontent.com/assets/172683/16701878/902cab9e-4517-11e6-9a16-df1f28bab564.png)

![screen shot 2016-07-08 at 2 23 40 pm](https://cloud.githubusercontent.com/assets/172683/16701882/98941a2e-4517-11e6-973b-27a9434f374c.png)

Using `"react-bootstrap-sweetalert": "^1.1.11",`

**Comment by djorg83** [comment]
looking into this now

**Comment by djorg83** [comment]
Ah, just noticed that you are on version 1.1.11.  Password type was added in 2.0.1

**Comment by jfeldstein** [comment]
Deep. Thank you for your help.
