### ISSUE TITLE
Alert Timeout Support

### ISSUE THREAD

**Issue by jundialwan** [djorg83/react-bootstrap-sweetalert#23]
Hi @djorg83 ,
This library is so cool. I love it.

However, is it possible to have timeout support?
Alert will self-close in given millisecond/second. 
I think it is a good idea to have timeout support.

Nice work, have a nice day. 
Thank you.

**Comment by jundialwan** [comment]
Oh, and maybe we can trigger a callback when timeout is ended.
Like, in example, we can automatically logout after alert ended in 5 seconds.

**Comment by djorg83** [comment]
👍
