### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by Horat1us** [djorg83/react-bootstrap-sweetalert#24]
Don't you consider to migrate components to TypeScript?
Will you accept PR if our team do it?

**Comment by djorg83** [comment]
Why?

**Comment by Horat1us** [comment]
We prefer to use strict types and tests in our financial projects and now migration one of our old project that use only JS.
So, we need to create own component with TS definitions and tests or modify yours.

**Comment by djorg83** [comment]
Not sure why you need third party code to be changed in order from you to test your code. And can't expect every package on npm to be rewritten to TS because of your testing needs.  Why exactly does this library need to be in TS for your tests to pass?
