### ISSUE TITLE
Warning: Failed prop type: The prop `onConfirm` is marked as required in `SweetAlert`, but its value is `undefined`.

### ISSUE THREAD

**Issue by harishmahajan** [djorg83/react-bootstrap-sweetalert#25]
I used 

             <SweetAlert 
             warning
             showCancel
             confirmBtnText="Yes, delete it!"
             confirmBtnBsStyle="danger"
             cancelBtnBsStyle="default"
             title="Are you sure?"
             onConfirm={this.deleteFile}
             onCancel={this.cancelDelete}
         >
             You will not be able to recover this imaginary file!
         </SweetAlert>

**Comment by djorg83** [comment]
Please include a sample of your usage

**Comment by harishmahajan** [comment]
sample added above

**Comment by harishmahajan** [comment]
solved by doing this.

<button onClick={() => this.setState({ show: true })}>Alert</button>
            <SweetAlert
                show={this.state.show}
                title="Demo"
                text="SweetAlert in React"
                onConfirm={() => this.setState({ show: false })}
            />
