### ISSUE TITLE
showConfirm={false} doesn't hide the confirm button

### ISSUE THREAD

**Issue by reneedudley** [djorg83/react-bootstrap-sweetalert#26]
Code that I'm using, 

`<SweetAlert error
                            showConfirm={false}
                            showCancel={false}
                            title={'Error'}
                            style={{ fontSize: 20 }} >
                    {'not today, satan'}
                </SweetAlert>`

The button still appears 
![screen shot 2018-04-18 at 11 54 21 am](https://user-images.githubusercontent.com/12837355/38946517-4c4a8b66-42ff-11e8-8c42-a725e4e3b39a.png)

**Comment by djorg83** [comment]
I'll look into this

**Comment by mealbarracin10** [comment]
i tried this example and it working, this is my code: 

    <SweetAlert
            title={<div>
              <form className="form-signin">
              <h1 className="h3 mb-3 font-weight-normal">Please sign in</h1>
              <input type="email" id="inputEmail" className="form-control" placeholder="Email address" required />
              <input type="email" className="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" />
              <input type="password" id="inputPassword" className="form-control" placeholder="Password" required />
              <button type="submit" className="btn btn-primary">Submit</button>
            </form>   
          </div>}
          onConfirm={this.onConfirm}
          showConfirm={false}>
        </SweetAlert>
