### ISSUE TITLE
Support popping up modal forms and not just a single input field

### ISSUE THREAD

**Issue by ruegreen** [djorg83/react-bootstrap-sweetalert#28]
Currently sweetalert does support popping up an alert that provides a single input field.  However for simple CRUD operations or smaller modal forms it would be great if we could build larger input forms and pop them up with data based to the alert via props for editing.  This would very useful when using larger data tables and editing a row of data.

**Comment by djorg83** [comment]
You can embedded any custom content that you want as children of the SweetAlert component.  This gives you the ability to embed an  entire form with multiple fields.

Alternativel, you can chain alerts one after another to gather one piece of data at a time.  

I don't think there is a big enough shared need by the community to merit adding native support for multiple inputs.  The idea of a prompt is to be simple.  You may want to explore using a true modal.

**Comment by ruegreen** [comment]
Ok well your first comment, where is this documented in your documentation on how to embedded content as a child of sweetalert and do you have an example I could follow to look at this option.  I also do not see a way, to return the data from the custom form once sweetalert is done.  While I can agree that we want to keep alerts simple, why not provide a simple form pop to provide easier ways to pop up modal forms over the top of existing dashboards, etc.  Seems to be a pretty sweet feature.  I will look for other products that can do modal form pops as well, I am sure someone has addressed this already.  Thank you in advance!

**Comment by djorg83** [comment]
Sorry for the extremely delayed response.

Embedding custom content within the sweetalert component is very simple.  You can see this done in every example on the documentation and demo site.

```<SweetAlert> ...anything you want here </SweetAlert>```
