### ISSUE TITLE
Alert icon stays set when the alert changes

### ISSUE THREAD

**Issue by AirborneEagle** [djorg83/react-bootstrap-sweetalert#31]
I have an alert that changes based on user input (strange use case, right? 😄 )

please see this sandbox:
https://codesandbox.io/s/54k30y94yp

the loading alert is not supposed to have any Icon, yet it shows the warning Icon from the alert that was showing before it.

I am at a total loss here. I kinda hope I am overlooking something simple. but at the same time, I don't really enjoy looking like a moron.

Anyways, please do forgive me if I am doing something dumb here, or overlooking something really simple.

**Comment by djorg83** [comment]
I'll look at this tomorrow.

**Comment by djorg83** [comment]
Sorry for taking so long to get to this.  The easiest way to mitigate this would be to provide a `type="default"` prop to the "loading" alert.  https://codesandbox.io/embed/9zvwp8v52w 

I'll leave this issue open until I fix the underlying issue that causes the `type` from the previous alert to be retained on the subsequent alert.

**Comment by wouter140** [comment]
This is also fixed in PR #50 and can be closed @djorg83
