### ISSUE TITLE
Add support for 'secondary' type for button 

### ISSUE THREAD

**Issue by sakul-budhathoki** [djorg83/react-bootstrap-sweetalert#32]
I got warning when used  `cancelBtnBsStyle="secondary"`

Warning Reference:  
![warning](https://user-images.githubusercontent.com/13379067/49438234-da7d0d00-f7e5-11e8-8c0d-3b983cb264bc.png)

But It works pretty fine, Reference: 
![secondarybutton](https://user-images.githubusercontent.com/13379067/49438283-07c9bb00-f7e6-11e8-8740-8098d6626cef.png)

**Comment by djorg83** [comment]
thanks.  i will fix this.

**Comment by Ignefolio** [comment]
Maybe change confirmBtnBsStyle, cancelBtnBsStyle to string so any class can be used?

**Comment by djorg83** [comment]
the upcoming 5.0 release will allow any string as the button BS style
