### ISSUE TITLE
Support re-ordering of buttons

### ISSUE THREAD

**Issue by rezaabedian** [djorg83/react-bootstrap-sweetalert#34]
Currently the Buttons.js doesn't allow for the Cancel and Confirm buttons to be re-ordered. It assumes that if `this.props.showConfirm === true` and  `this.props.showCancel === true` that it should render the Cancel button first and then the Confirm button.  This should be a relatively easy fix if we just want to solve for consumers re-ordering the buttons. If we want to support further customization, we could potentially use a render prop.

**Comment by djorg83** [comment]
You could hide both buttons and render you own buttons within the sweet alert content.  I'll see about using render props of some other sort of customization for the buttons

**Comment by wouter140** [comment]
I added support for re-ordering in PR #51 with the `reverseButtons` property, like swal has it. I also added the option to fully customize the actions with the `customActions` property.
