### ISSUE TITLE
how to access the input in the onconfirm function?

### ISSUE THREAD

**Issue by simkimsia** [djorg83/react-bootstrap-sweetalert#35]
How do I retrieve the value of the input inside the onConfirm function? This is for type="input"

**Comment by simkimsia** [comment]
okay I figured out that the onConfirm will pass the input value as the first argument into the onConfirm callback.

Thanks.. I will send a PR to the documentation to make this clear

**Comment by abbeyseto** [comment]
> okay I figured out that the onConfirm will pass the input value as the first argument into the onConfirm callback.
> 
> Thanks.. I will send a PR to the documentation to make this clear

How does the onConfirm pass the input value as the first argument? I mean how do i retrieve this value? I'm stuck at this.

**Comment by simkimsia** [comment]
@abbeyseto just look at the change I made in my PR https://github.com/djorg83/react-bootstrap-sweetalert/pull/36/commits/fe459fbd252f13011ac421fb90c95d194482c4ce#diff-04c6e90faac2675aa89e2176d2eec7d8R47

**Comment by djorg83** [comment]
PR merged.  See README to how to get input value.
