### ISSUE TITLE
Sweetalert not working on nodejs 10.13

### ISSUE THREAD

**Issue by namnguyen2091** [djorg83/react-bootstrap-sweetalert#37]
I try to follow this link https://stackoverflow.com/questions/41006087/add-sweet-alert-popup-to-button-in-react-component/41006372#41006372 but I got an error
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
Check your code at Company.js:15.
I dont know why what happened, please help me how to use this?

**Comment by djorg83** [comment]
Im going to need more information to debug this.    I dont know what Company.js is.  This project contains no such file.

**Comment by namnguyen2091** [comment]
Thanks for your reply. I try to follow link above and it's not working so I try other way, maybe I'm new user so I dont know how it works. This is my code changed and its working fine.
`<button onClick={() => this.showPopupConfirm('Save changes for client', 'Are you sure?', () => this.handleDeleteClick, 'custom') }>Delete</button>
showPopupConfirm(title, message, callBack, style) {
    this.setState({
      alert: (
          <SweetAlert
              info
              showCancel
              confirmBtnText = "Yes"
              cancelBtnText = "No"
              confirmBtnBsStyle="danger"
              cancelBtnBsStyle = "primary"
              title = {title}
              onConfirm = {callBack()}
              onCancel = {this.hideAlert}
          >
            {message}
          </SweetAlert>
      )
    });
  }
`
Thanks for your awesome component.

**Comment by ntanwir** [comment]
@namnguyen2091 I have a similar implementation but getting `TypeError: Cannot read property 'setState' of undefined` error. 
[This is the issue link](https://github.com/djorg83/react-bootstrap-sweetalert/issues/71) 
can you please help me? thanks a ton.
