### ISSUE TITLE
Writing text bellow the buttons

### ISSUE THREAD

**Issue by itsthomas** [djorg83/react-bootstrap-sweetalert#39]
It would be great, if we could add some text bellow the buttons.
At the moment I don't think that it's possible.

**Comment by djorg83** [comment]
You can do this by hiding the existing buttons and making your own

```
# add this prop to hide the confirm button
showConfirm={false}
```

Then just make your own buttons and embed them as children between the <SweetAlert> ...content and buttons here </SweetAlert>

If using this approach, you will need to implement your own click handler to close the alert.

**Comment by djorg83** [comment]
Closing for now.  I will reopen if this is not a sufficient solution.
