### ISSUE TITLE
Feature Request : Change the time it will take for the alert to be displayed

### ISSUE THREAD

**Issue by yafkari** [djorg83/react-bootstrap-sweetalert#40]
Hello,

Thank's for this great resources !

I think it could be even better if we could set the time it will take for the alert to be displayed.

Thank's !

**Comment by djorg83** [comment]
Im not sure I understand your request.  Do you want have a delay before showing the alert? or automatically close the alert after a certain amount of time had passed?

**Comment by djorg83** [comment]
Closing due to lack of response.
