### ISSUE TITLE
Custom buttons

### ISSUE THREAD

**Issue by jctiradopatientnow** [djorg83/react-bootstrap-sweetalert#42]
I want to use custom buttons. Something like "YES", "YES TO ALL", "NO"

For what I can see it only supports confirm and cancel button.

**Comment by djorg83** [comment]
ill see if i can add this for the upcoming 5.0 release

**Comment by wouter140** [comment]
I added support for custom actions in PR #51 with the `customActions` property. With this you can fully change the buttons to anything custom.

**Comment by jctiradopatientnow** [comment]
Excellent.

Thanks!
