### ISSUE TITLE
Updating content which changes alert size does not update position

### ISSUE THREAD

**Issue by wouter140** [djorg83/react-bootstrap-sweetalert#45]
I'm updating my modal after I have loaded some data which then changes the modal size significantly. After this change, the modal stays in the same position from the top of the document.
Is there any way to recalculate the modal position?

**Comment by wouter140** [comment]
Can be fixed with the same styling changes from issue #46 with pull request #47

**Comment by djorg83** [comment]
I'll check if the #47 PR fixed this also.

**Comment by wouter140** [comment]
Fixed in PR #47 and tested
