### ISSUE TITLE
Deprecated methods in React 16.9.0

### ISSUE THREAD

**Issue by MarkEhr** [djorg83/react-bootstrap-sweetalert#48]
The methods `componentWillMount`, `componentWillReceiveProps` and `componentWillUpdate` are deprecated and they throw a warning in React 16.9.0. They will be removed in React 17 and this component would stop working.

**Comment by wouter140** [comment]
I fixed the deprecation warning in PR #50 and updated all the functionality to be complient with the new version.

**Comment by caleb-harrelson** [comment]
When might this go out in a release?

**Comment by djorg83** [comment]
I will release v5.1.0 soon.  I need some time to test the new functionality and make release notes.

**Comment by djorg83** [comment]
v5.1.0 is now available
