### ISSUE TITLE
onConfirm not called when specifying show property

### ISSUE THREAD

**Issue by wouter140** [djorg83/react-bootstrap-sweetalert#56]
I'm using the show property to show and hide the alert as this is the easiest for me as I also update the content and stuff.
However, since the new version onConfirm does not seem to get called when specifying the show property and thus my alerts are never closing.
I looked at the callstack and some debugging and it seems that because of the default closeanim activation https://github.com/djorg83/react-bootstrap-sweetalert/blob/8161f5d59e89be4c0a18133465fe6f4b97ee66a3/src/components/SweetAlert.tsx#L469
Should this not default to false as the default closeanim property is unset?

**Comment by brunnomatheuus** [comment]
+1

**Comment by brunnomatheuus** [comment]
And the buttons had style changes

**Comment by djorg83** [comment]
Im looking into this right now

**Comment by djorg83** [comment]
Fixed this with v5.1.6.

@brunnomatheuus what style changes are you referring to?  The default button type for the cancel button, or the change to using flex positioning?
