### ISSUE TITLE
Breaks tests with the default CRA setup

### ISSUE THREAD

**Issue by mjetek** [djorg83/react-bootstrap-sweetalert#59]
Hi, 
The package which is published to npm is using import syntax and it breaks tests when your are using default setup created by `create-react-app`.
I get this error when running tests which use `react-bootstrap-sweetalert`:
```
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import SweetAlert from "./components/SweetAlert";
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module
```
I've created this simple example where you can see the issue
https://github.com/mjetek/test-react-bootstrap-sweetalert

**Comment by djorg83** [comment]
resolved with v5.1.9
