### ISSUE TITLE
Set `confirmBtnText` property type to node

### ISSUE THREAD

**Issue by marceloemanoel** [djorg83/react-bootstrap-sweetalert#6]
although the property name states that its type should be text it would be nice to have it typed as node (https://facebook.github.io/react/docs/typechecking-with-proptypes.html). This would allow the content of the button include icons in the text like this:

```javascript
const confirmButtonText= (
<span>
   <i className="fa fa-play"/> Start
</span>
);

 <SweetAlert
        title="Play"
        success
        confirmBtnText={confirmButtonText}
        onConfirm={...}>
        {message}
 </SweetAlert>
```

The current behaviour display a warning in this situation.

```
Warning: Failed prop type: Invalid prop `confirmBtnText` of type `object` supplied to `SweetAlert`, expected `string`.
```

**Comment by djorg83** [comment]
Done.  Published version 2.2.2

Happy Halloween! 

![image](https://cloud.githubusercontent.com/assets/3258109/19874461/c95af978-9f9b-11e6-989b-7f3edd43ac97.png)
