### ISSUE TITLE
showCloseButton option does not show close button(React 16.13.1)

### ISSUE THREAD

**Issue by SungYoun** [djorg83/react-bootstrap-sweetalert#67]
hello~~ T0T;;;
I am developing in React 16.13.1, but the close button is not visible with showCloseButton option.
What should I do?

p.s react-bootstrap-sweetalert version 5.1.9

**Comment by bryandidur** [comment]
Same here!

**Comment by djorg83** [comment]
Im checking on this now

**Comment by djorg83** [comment]
Are you by chance not providing `props.onCancel`?

I've updated the docs to note that you cannot use the close button without handling onCancel.

https://github.com/djorg83/react-bootstrap-sweetalert#propsshowclosebutton

Please advise if this was indeed the problem

**Comment by SungYoun** [comment]
thank you. Thank you very much.
