### ISSUE TITLE
string ref, "container", has been found within a strict mode tree

### ISSUE THREAD

**Issue by dgour007** [djorg83/react-bootstrap-sweetalert#73]
React app running in strict mode. Following warning is received on SweetAlert render:

_Warning: A string ref, "container", has been found within a strict mode tree. String refs are a source of potential bugs and should be avoided. We recommend using useRef() or createRef() instead. Learn more about using refs safely here: https://fb.me/react-strict-mode-string-ref
    in div (created by Overlay)
    in Overlay (created by SweetAlert)
    in div (created by SweetAlert)_

**Comment by djorg83** [comment]
What version are you using? This was already reported and fixed.

**Comment by dgour007** [comment]
Thanks..Yes its resolved in the latest. I was using older version..
