### ISSUE TITLE
Closing by clicking outside (allowOutsideClick=true) doesn't call callback

### ISSUE THREAD

**Issue by jgentes** [djorg83/react-bootstrap-sweetalert#8]
I'm seeing this behavior, although I am launching sweetalert on top of a react-bootstrap modal, so not sure if that's affecting it. Here's the initial issue on sweetalert:

https://github.com/t4t5/sweetalert/issues/299

This was apparently fixed here: https://github.com/t4t5/sweetalert/commit/7720ccafea1a259165207ee9842da11c770f6420

**Comment by djorg83** [comment]
allowOutsideClick isn't a supported property.  Are you requesting this to be added?

**Comment by jgentes** [comment]
Hi @djorg83, I'm not specifically requesting that property. The 'outside click' functionality seems to work fine. If I click outside of the alert box, it disappears (unless this isn't intended.. that could be a result of the underlying modal window). What I'm really after is when that click occurs, it triggers the onCancel event.

**Comment by djorg83** [comment]
Ok. I see what you mean. This seems more like a defect within your application. Is the outside click somehow changing the state of your app and causing the sweet alert to no longer be rendered?

**Comment by jgentes** [comment]
I'm not sure I'd call it a defect.. I have to render the sweetalert on top of the modal, otherwise it won't show. As a result, yes - when the modal disappears, it prevents sweetalert from rendering.

So I guess that's the cause, but I'm not sure how to get sweetalert to appear in front of the modal without making it part of the modal component.

**Comment by jgentes** [comment]
As a workaround, I can specify `backdrop='static'` on the Modal to prevent background clicks from hiding it.

**Comment by lasergoat** [comment]
For anyone struggling with the `onOutsideClick` function also calling the `onCancel` a simple hackish workaround is this:

```JSX
<SweetAlert
  show={showConfirm}
  title="Weekly Summary Email"
  text={'....?'}
  showCancelButton
  onCancel={() => this.handleChoice(false)}
  onConfirm={() => this.handleChoice(true)}
  onOutsideClick={() => {
    this.wasOutsideClick = true;
    this.setState({ showConfirm: false })
  }}
  confirmButtonText="Yes, Definitely"
  cancelButtonText="Nope"
/>

// then in handleChoice just do:

  handleChoice(choice) {
    if (this.wasOutsideClick) {
      return;
    }
    // ...

```

**Comment by djorg83** [comment]
Closing this as a non-issue.  If this is still a problem, please reply or submit a PR.
