### ISSUE TITLE
Does not support showConfirmButton={false}

### ISSUE THREAD

**Issue by joshreid** [djorg83/react-bootstrap-sweetalert#9]
Cannot hide the cancel button to show an alert with no buttons.

Should be able to pass prop:
showConfirmButton={false}

**Comment by djorg83** [comment]
What is your use case for having no buttons? Just curious.

**Comment by joshreid** [comment]
Cool as - to use during ajax request as user feedback/msg and then hide on successful response.

**Comment by djorg83** [comment]
Like a spinner?

**Comment by joshreid** [comment]
At that point, but then changing the the waiting state of the alert to one of user feedback eg: success/danger + messaging and show buttons once we have response. Could do with hidden class on confirm button - but swal does support showConfirmButton, so just wondered whether we could add here.

**Comment by djorg83** [comment]
OK. I'll add it.

**Comment by joshreid** [comment]
Great, thank you!

**Comment by djorg83** [comment]
implemented as `props.showConfirm`.  Defaults to true.
